plugins {
    id 'mule-linter.groovy-common-conventions'
    id 'mule-linter.maven-publish-conventions'
    id 'org.gradlex.maven-plugin-development'
}

dependencies {
    implementation 'org.apache.maven.plugins:maven-plugin-plugin:3.13.1'
    compileOnly 'org.apache.maven.plugin-tools:maven-plugin-annotations:3.13.1'
}