#%RAML 1.0 Library
usage: Music Factory API
traits:
  correlationRequired:
    headers:
      correlation_id:
        type: string
        required: true

  contentTypeRequired:
      headers:                
        Content-Type: 
          displayName: Content-Type
          type: string
          required: false
          example: application/json

  clientIdRequired:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

    responses:
      401:
        description: Unauthorized or invalid client application credentials
      500:
        description: Bad response from authorization server, or WSDL SOAP Fault error
  errorResponsesRequired: !include error-responses-trait.raml