#%RAML 1.0 NamedExample
{
  "apiInError" : "some-api",
  "flowInError" : "flow-name",
  "correlationId" : "e4c01q",
  "error": {
    "type": "WSC:Cannot Dispatch",
    "detail": "An error occurred while sending the SOAP request"
  }
}