#%RAML 1.0 DataType

type: object

properties:
  customerId:
    required: true
    type: string
    example: "0003"
  customerName:
    required: true
    type: string
    example: Paula Adam
  salesOrderId:
    required: true
    type: string
    example: A1003
  lineItems:
    required: true
    type: array
    items: []
    example: []